---
- hosts: leafs
  become: yes
  tasks:
    - name: Enable Quagga Zebra
      lineinfile:
        dest: /etc/quagga/daemons
        line: "zebra=yes"
        regexp: "zebra="
      notify: restart quagga service

    - name: Enable Quagga BGP
      lineinfile:
        dest: /etc/quagga/daemons
        line: "bgpd=yes"
        regexp: "bgpd="
      notify: restart quagga service

    - name: Copy Interfaces File
      copy:
        src: /roles/{{ansible_hostname}}/interfaces
        dest: /etc/network/interfaces

  handlers:
    - include: handlers/main.yml
