---
- hosts: network
  tasks:
    # - name: Ping Test
    #   command: ping {{item}}
    - debug:
      msg: {{item}}
      with_items:
        - '{leaf01: "10.1.1.1"}'
        - '{leaf02: "10.1.1.2"}'
        - '{leaf03: "10.1.1.3"}'
        - '{leaf04: "10.1.1.4"}'
        - '{spine01: "10.100.100.1"}'
        - '{spine02: "10.100.100.2"}'
        - '{exit01: "10.255.255.1"}'
        - '{exit02: "10.255.255.2"}'
