---
- name: Enable swp1
  blockinfile:
    dest: /etc/network/interfaces
    marker: "## {mark} Ansible Managed Configuration ##"
    content: |
      auto swp1
      iface swp
    backup: yes
    #validate: ifreload -a -s

- name: Enable Eth0 for dhcp
  blockinfile:
    dest: /etc/network/interfaces
    marker: "## {mark} Ansible Managed Configuration ##"
    content: |
      auto eth0
      iface eth0 inet dhcp
    backup: yes
    #validate: ifreload -a -s
