---
- name: Enable Eth0 for dhcp
  blockinfile:
    dest: /etc/network/interfaces
    marker: "# eth0"
    content: |
      auto eth0
      iface eth0 inet dhcp

- name: Set Leaf01 Loopback IP
  set_fact:
    loopback_ip: "10.1.1.1/32"
  when: ansible_hostname == "leaf01"

- name: Set Leaf02 Loopback IP
  set_fact:
    loopback_ip: "10.1.1.2/32"
  when: ansible_hostname == "leaf02"

- name: Set Leaf03 Loopback IP
  set_fact:
    loopback_ip: "10.1.1.3/32"
  when: ansible_hostname == "leaf03"

- name: Set Leaf04 Loopback IP
  set_fact:
    loopback_ip: "10.1.1.4/32"
  when: ansible_hostname == "leaf014"

- name: Configure the loopback interface
  blockinfile:
    dest: /etc/network/interfaces
    marker: "# lo"
    content: |
      auto lo
      iface lo inet loopback
        address {{loopback_ip}}
